name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Rust Format and Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown
      - run: cargo fmt -- --check

      - run: cargo clippy --locked --all-targets -- -D warnings
      # profiling & tracy features can't be both enabled at the same time in the demo. This is a limitation of the `profiling` crate. 
      - run: cargo clippy --locked --all-features -- -D warnings
      - run: cargo clippy --locked --all-targets --features puffin -- -D warnings
      - run: cargo clippy --locked --all-targets --features tracy -- -D warnings

      - run: cargo check --locked --target wasm32-unknown-unknown

      - run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: '-D warnings'
